const dorms = [
    { name: "Harrington Hall", Price: "$$", Gender: "All Gender", RoomType: "Double Room", Bathroom: "Community" },
    { name: "Keathley Hall", Price: "$$", Gender: "All Gender", RoomType: "Single, Suite", Bathroom: "Suite" },
    { name: "Schuhmacher Hall", Price: "$$", Gender: "All Gender", RoomType: "Single, Suite", Bathroom: "Suite" },
    { name: "Moses Hall", Price: "$$", Gender: "All Gender", RoomType: "Double Room", Bathroom: "Community" },
    { name: "Wells Hall", Price: "$$$", Gender: "Single Gender by Room", RoomType: "Double Room", Bathroom: "Semi-Private" },
    { name: "Neeley Hall", Price: "$$$", Gender: "All Gender", RoomType: "Double Room", Bathroom: "Semi-Private" },
    { name: "McFadden Hall", Price: "$$$", Gender: "All Gender", RoomType: "Double Room", Bathroom: "Semi-Private" },
    { name: "Leggett Hall", Price: "$$", Gender: "Female", RoomType: "Double Room", Bathroom: "Semi-Private" },
    { name: "Hughes Hall", Price: "$$", Gender: "All Gender", RoomType: "Single", Bathroom: "Suite" },
    { name: "Walton Hall", Price: "$", Gender: "All Gender", RoomType: "Single, Suite", Bathroom: "Suite" },
    { name: "Hard Hall", Price: "$", Gender: "All Gender", RoomType: "Single, Suite", Bathroom: "Suite" },
    { name: "Haas Hall", Price: "$$$", Gender: "All Gender", RoomType: "Double Room", Bathroom: "Semi-Private" },
    { name: "Fowler Hall", Price: "$$", Gender: "All Gender", RoomType: "Single, Suite", Bathroom: "Suite" },
    { name: "Davis-Gary Hall", Price: "$$", Gender: "Female", RoomType: "Single Room", Bathroom: "Community" },
    { name: "Eppright Hall", Price: "$$$", Gender: "Single Gender by Room", RoomType: "Double Room", Bathroom: "Semi-Private" },
    { name: "Hobby Hall", Price: "$$$", Gender: "Single Gender by Room", RoomType: "Double Room", Bathroom: "Semi-Private" },
    { name: "Underwood Hall", Price: "$$$", Gender: "Female", RoomType: "Double Room", Bathroom: "Semi-Private" },
    { name: "Lechner Hall", Price: "$$$", Gender: "Single Gender by Room", RoomType: "Double Room", Bathroom: "Semi-Private" },
    { name: "Clements Hall", Price: "$$$", Gender: "Single Gender by Room", RoomType: "Double Room", Bathroom: "Semi-Private" },
    { name: "Rudder Hall", Price: "$$$", Gender: "Female", RoomType: "Double Room", Bathroom: "Semi-Private" },
    { name: "Appelt Hall", Price: "$$$", Gender: "Male", RoomType: "Double Room", Bathroom: "Semi-Private" },
    { name: "Hullabaloo Hall", Price: "$$$$", Gender: "All Gender", RoomType: "Single, Double, Suite", Bathroom: "Semi-Private, Suite" },
    { name: "Mosher Hall", Price: "$$$", Gender: "All Gender", RoomType: "Suite", Bathroom: "Suite" },
    { name: "Dunn Hall", Price: "$$$", Gender: "All Gender", RoomType: "Suite", Bathroom: "Suite" },
   
];