{Name:"4th floor Annex", preference:},
{Name:"5th floor Annex", preference:},
{Name:"ILCB", preference:},
{Name:"Cushing Library", preference:},
{Name:"MSC", preference:},
{Name:"Evans Library", preference:},
{Name:"Blocker", preference:},
{Name:"Zachry", preference:},
{Name:"Langford", preference:},
{Name:"Harrington", preference:},
{Name:"Wehner", preference:},
{Name:"Rudder", preference:},
